### ISSUE TITLE
Can you make graphql a peer dependency?

### ISSUE THREAD

**Issue by adamkl** [brysgo/graphql-mask#15]

**Comment by brysgo** [comment]
*No reponse provided*

**Comment by brysgo** [comment]
🤣 Just kidding, sounds like a reasonable ask. Is there a good way to do this without breaking things for other people?

**Comment by adamkl** [comment]
Sorry to leave this sleeping for so long, but now I have a need. :wink: 

The `graphql-proxy` I'm working on has a peer-dependency to `graphql` and an explicit dependency on `graphql-mask`, I have to pin my version to the same version used by `graphql-mask`. And by extension, anyone who ends up using `graphql-proxy` will need to pin their version of `graphql` as well. It'll end up being a pain. 

How about just bumping the semver major and pushing a new version that has `graphql` as a peer dependency? That shouldn't break any existing users.

**Comment by brysgo** [comment]
@adamkl - I'm down, lets do it.

**Comment by brysgo** [comment]
@adamkl - let me know if the latest version does the trick, I kinda messed up the whole semver thing by leaving the patch version the same, but it shouldn't make a difference.

**Comment by adamkl** [comment]
This works for me. Thanks!
