### ISSUE TITLE
TypeError: Cannot read property 'kind' of null when masking input types

### ISSUE THREAD

**Issue by adamkl** [brysgo/graphql-mask#16]
We're seeing an issue when we pass a query/mutation that uses variables based on input types that don't exist in the schema being used to mask the query. (see referenced PR for unit tests)

```bash
TypeError: Cannot read property 'kind' of null

      29 |   var incrementalAst = parse(query);
      30 |   var errors;
    > 31 |   while ((errors = validate(astSchema, incrementalAst, rules)).length > 0) {
      32 |     console.log(errors);
      33 |     var nodes = [].concat.apply(
      34 |       [],

      at typeFromAST (node_modules/graphql/utilities/typeFromAST.js:32:16)
      at typeFromAST (node_modules/graphql/utilities/typeFromAST.js:37:17)
      at TypeInfo.enter (node_modules/graphql/utilities/TypeInfo.js:157:54)
      at Object.enter (node_modules/graphql/language/visitor.js:363:16)
      at visit (node_modules/graphql/language/visitor.js:254:26)
      at visitUsingRules (node_modules/graphql/validation/validate.js:74:22)
      at validate (node_modules/graphql/validation/validate.js:59:10)
      at graphqlMask (src/index.js:31:20)
```

I've console.logged the validation errors and printouts of the interim AST as `graphql-mask` iterates on the queries added in the unit tests, and it looks like the query gets into a strange state that `graphql` can't validate on the following pass.

```bash  
  console.log src\index.js:32
    [ GraphQLError {
        message: 'Unknown type "FizzFilter".',
        locations: [ [Object] ],
        path: undefined },
      GraphQLError {
        message: 'Cannot query field "fizz" on type "Query".',
        locations: [ [Object] ],
        path: undefined } ]

  console.log src\index.js:60
    query getFizz($filter: null!) <-- wha?


  console.log src\index.js:32
    [ GraphQLError {
        message: 'Unknown type "FizzInput".',
        locations: [ [Object] ],
        path: undefined },
      GraphQLError {
        message: 'Cannot query field "fizz" on type "Mutation".',
        locations: [ [Object] ],
        path: undefined } ]

  console.log src\index.js:60
    mutation fizzer($data: null!) <-- wha?
```

**Comment by brysgo** [comment]
Thanks for this @adamkl ! The way to fix this would be to add a rule that makes that invalid graphql. The rules in this project mimic the actually validation rules used by graphql and supplements them.

**Comment by brysgo** [comment]
I will get to it as soon as I can.

**Comment by adamkl** [comment]
I can try my hand at fixing this one in my PR if you’d like. I just wanted your take on how I should approach it. 

I’ll take a closer look at how the validation rules work. 

If I can’t figure it out, I’ll come back begging for help. 🙃

**Comment by brysgo** [comment]
@sjensen85 fixed this and I published the fix in version 0.0.11. Please confirm that this is fixed.

**Comment by adamkl** [comment]
@brysgo @sjensen85 Thanks guys! We'll pull the new version today and confirm.

**Comment by brysgo** [comment]
Is this issue resolved?
